FROM rancher/cli:latest

LABEL org.opencontainers.image.authors="Ayaz BADOURALY" \
      org.opencontainers.image.description="rancher-cli for gitlab-ci"

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
