FROM alpine:latest

# Set non-built-time labels
LABEL org.opencontainers.image.authors="Ayaz BADOURALY"
LABEL org.opencontainers.image.description="Smallest docker image with curl, jq and yq"

# Install curl, jq and yq
RUN apk add --no-cache curl jq yq
