FROM alpine:latest

# Set non-built-time labels
LABEL org.opencontainers.image.authors="Ayaz BADOURALY"
LABEL org.opencontainers.image.description="Smallest docker image with curl and jq"

# Install curl and jq
RUN apk add --no-cache curl jq
