#!/bin/bash
#
# This file  adds  a `post_build` step  to  the automated build process.  For further infomation,
# see  https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands
#

# Retrieve current base image tag and tag the built image
CUSTOM_TAG=`sed -E "s/^FROM .*:(.*)$/\1/" Dockerfile`

docker tag $IMAGE_NAME $DOCKER_REPO:$CUSTOM_TAG
docker push $DOCKER_REPO:$CUSTOM_TAG
