#!/bin/bash
#
# This file implements a `pre_build` hook executed during automated builds.
# See https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks
#

# Set custom envvars
CUSTOM_TAG=`docker run --rm gempesaw/curl-jq sh -c "curl -s https://hub.docker.com/v2/repositories/rancher/cli/tags/ | jq -r '.results[1].name'"`

# Print custom envvars
echo "Custom environment variables set by the pre_build hook:"
echo " - CUSTOM_TAG=$CUSTOM_TAG"

# Update base image with current tag
sed -Ei "s,^FROM (.*):.*$,FROM \1:$CUSTOM_TAG," Dockerfile
