FROM rancher/cli:v0.6.12

LABEL org.opencontainers.image.authors="Ayaz BADOURALY"
LABEL org.opencontainers.image.description="rancher-cli for gitlab-ci"

COPY entrypoint.sh /

ENTRYPOINT [ "/entrypoint.sh" ]
