#!/bin/bash
#
# This file implements a `post_checkout` hook executed during automated builds.
# See https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks
#

# Print envvars
echo "Utility environment variables set by the build process:"
echo " - SOURCE_BRANCH=$SOURCE_BRANCH"
echo " - SOURCE_COMMIT=$SOURCE_COMMIT"
echo " - COMMIT_MSG=$COMMIT_MSG"
echo " - DOCKER_REPO=$DOCKER_REPO"
echo " - DOCKER_TAG=$DOCKER_TAG"
echo " - IMAGE_NAME=$IMAGE_NAME"

# Set custom envvars
BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
REVISION_LONG=`git rev-parse HEAD`
REVISION_SHORT=`git rev-parse --short HEAD`
SOURCE=`git config --get remote.origin.url | sed -r "s,^git@(.*):(.*)$,https://\1/\2," | sed -r "s,^(.*)\.git$,\1,"`
DOCKER_CONTEXT=`echo "$SOURCE/tree/$REVISION_SHORT/$(git rev-parse --show-prefix)" | head --bytes -2`

# Print custom envvars
echo "Custom environment variables set by the post_checkout hook:"
echo " - BUILD_DATE=$BUILD_DATE"
echo " - DOCKER_CONTEXT=$DOCKER_CONTEXT"
echo " - REVISION_LONG=$REVISION_LONG"
echo " - REVISION_SHORT=$REVISION_SHORT"
echo " - SOURCE=$SOURCE"

# Patch the Dockerfile ( see http://label-schema.org/ )
echo "LABEL org.opencontainers.image.created=$BUILD_DATE"                     >> Dockerfile
echo "LABEL org.opencontainers.image.documentation=$DOCKER_CONTEXT/README.md" >> Dockerfile
echo "LABEL org.opencontainers.image.revision=$REVISION_LONG"                 >> Dockerfile
echo "LABEL org.opencontainers.image.source=$SOURCE"                          >> Dockerfile
