# zsh config file for oh-my-via

# Path to your oh-my-zsh installation.
export ZSH=/opt/oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="oh-my-via/via"

# Initialize oh-my-zsh
source $ZSH/oh-my-zsh.sh

# vim: ft=zsh fenc=utf-8

