FROM rancher/cli2:v2.0.6

LABEL org.opencontainers.image.authors="Ayaz BADOURALY"
LABEL org.opencontainers.image.description="rancher-cli for gitlab-ci"

COPY entrypoint.sh /

ENTRYPOINT [ "/entrypoint.sh" ]
