#!/usr/bin/env bash

# Set bash safeguard
set -euo pipefail

# Set custom envvars
CUSTOM_TAG=`docker run --rm badouralix/curl-jq sh -c "curl -s https://hub.docker.com/v2/repositories/rancher/cli2/tags/ | jq -r '.results[1].name'"`

# Print custom envvars
echo "Fetched custom tag $CUSTOM_TAG"
echo "::set-output name=extra_tags::$IMAGE_NAME:$CUSTOM_TAG"

# Update base image with current tag
sed -Ei "s,^FROM (.*):.*$,FROM \1:$CUSTOM_TAG," Dockerfile

# Print patched dockerfile
echo "::group::Patched dockerfile"
cat Dockerfile
echo "::endgroup::"
