#!/bin/bash
#
# This file implements a `pre_push` hook executed during automated builds.
# See https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks
#

# Retrieve current base image tag and tag the built image
CUSTOM_TAG=`sed -nE "s/^FROM .*:(.*)$/\1/p" Dockerfile`

docker tag $IMAGE_NAME $DOCKER_REPO:$CUSTOM_TAG
docker push $DOCKER_REPO:$CUSTOM_TAG
