name: schedule

on:
  schedule:  # See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  - cron: "0 0 * * *"
  workflow_dispatch:  # See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch

jobs:
  schedule:
    name: schedule
    strategy:
      matrix:
        image_name:
        - caddy-dns-ovh
        - curl-http2
        - curl-jq
        - curl-jq-yq
        - easy-blake2s
        - oh-my-via
        - python-scrapy
        - rancher-cli
        - toolbox
    uses: ./.github/workflows/buildx.yaml
    with:
      image_name: ${{ matrix.image_name }}
      image_tag: latest
